
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      

---


apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379


---


apiVersion: v1
kind: Service
metadata:
  name: img-svc
spec:
  type: NodePort
  selector:
    app: img-svc
  ports:
    - protocol: TCP
      port: 8080

